/* css1 style sheet for web contents
   by Yamamoto Hiroshi  */
address
{
	font-size: 80%;
}
body
{
	background-image: url(repeat-y32x8-2.png);
	background-color: #eeffff;
	background-repeat: repeat-y;
	color: #333311;
	line-height:1.2em;
	margin: 1em 1em 1em 3em;
	}
div.embox
{
	background-color: #eeffff;
	border: thin #556644 dotted;
	color: #333311;
	margin: 1em 2em 1em 2em;
	padding: 0.5em;
}
div.picture
{
	float: right;
}
em.ans
{
	background-color: #eeffff;
	border: thin #556644 solid;
	color: #ee1100;
	font-style: normal;
	font-weight: normal;
	margin: 0.2em;
	padding: 0.1em;
	white-space: pre;
}
h1
{
	background-color: #eeffff;
	background-image: url(repeat4x8-2.png);
	background-repeat: repeat;
	border-bottom: medium #556644 solid;
	border-right: thick #556644 solid;
	color: #333311;
	font-size: 120%;
	font-weight: bold;
	letter-spacing:0.2em;
	line-height:1.2em;
	margin: 0 0 1em 0;
	padding: 0.3em;
	text-align: center;
}
h1.title
{
	font-size: 141%;
	padding: 0.5em;
}
p.picture
{
	font-size: 70%;
	text-align: center;
}
